### ISSUE TITLE
Exception when starting activity com.unity3d.player.UnityPlayerNativeActivity android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by yuri-goncharov** [googleads/googleads-mobile-plugins#89] opened 2015-03-31 09:06 UTC
Plugin Version: 2.2
Unity Version: both 4.6.4f1, 5.0.0p3
Google Play Services Version: 23
Android SDK: API 22
---- DEVICE ----
Phone: Samsung GT-N7000
Android: 4.0.3.
Google Play Services: 6.5.99(1642632-036)

Steps to reproduce:
1. Run Unity Game on Device and Load Banner
2. Quit from the Game
3. Run Game Again(without delays)
4. Game is crashed and I see black screen. 

Logcat:
03-31 11:55:33.514    1854-1864/? E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
03-31 11:55:33.539    1854-1864/? W/ActivityManager﹕ Exception when starting activity com.gipnetix.esaga/com.unity3d.player.UnityPlayerNativeActivity
    android.os.TransactionTooLargeException
            at android.os.BinderProxy.transact(Native Method)
            at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:669)
            at com.android.server.am.ActivityStack.realStartActivityLocked(ActivityStack.java:631)
            at com.android.server.am.ActivityStack.startSpecificActivityLocked(ActivityStack.java:764)
            at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1669)
            at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1081)
            at com.android.server.am.ActivityStack.activityPaused(ActivityStack.java:993)
            at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:4339)
            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:386)
            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:1681)
            at android.os.Binder.execTransact(Binder.java:338)
            at dalvik.system.NativeStart.run(Native Method)

Workaround: No. But everything works fine if I comment all AdMob plugin calls

**Comment by jjjuande** [comment] 2015-03-31 09:11
I think one solution is to destroy the banner when the app is backgrounded. Just destroy it in OnDisable(), and recreate it in OnEnable(). This should fix the issue. (I guess)

**Comment by yuri-goncharov** [comment] 2015-03-31 09:33
Sure. I destroy banner and interstitial. Here is my code:

	public void OnApplicationQuit(){
		if (bannerView != null) {
			bannerView.Destroy();
			Debug.Log ("Clear Banner");
		}

		if (interstitialView != null) {
			interstitialView.Destroy();
			Debug.Log ("Clear Interstitial");
		}
	}

And I see my logs and Plugin logs: 03-31 13:17:44.714  27542-27542/? D/GoogleMobileAdsUnityPlugin﹕ Calling destroy() on Android

**Comment by yuri-goncharov** [comment] 2015-03-31 09:55
Same happens with unity/samples/HelloWorld but you have to run/quit about 3-5 times.
Also the issue reproducible on my Samsung GT-N7000 and customer's ASUS Fonepad ME371MG. But Game works good on LG G2

**Comment by jjjuande** [comment] 2015-03-31 10:25
I'm using Unity 5.0.0p3 and I'm unable tu reproduce the issue on my Nexus 5. Tried several times quit [button with a call to Application.Quit()], start, quit, start. I made as fast as I could, but no success.

What "Quit from game" means?
1. Application.Quit()
2. Pressing Home button.

From the log you posted, it looks like your activity is resuming. Then I guess you are pressing the Home button to exit your game.

Can you use OnDisable() instead of OnApplicationQuit()?

**Comment by yuri-goncharov** [comment] 2015-03-31 11:15
I also can't reproduce problem on LG G2 and Samsung S2. However it reproducible on Samsung Galaxy Tab 2 and Samsung Galaxy Note. Probably it depends on Android version and Google Play Services version.

"Quit from game" means "Application.Quit()"

I suppose that game doesn't really quit. It has some unclosed requests(sessions). So when I try to re-launch game it still is running and Android tries to resume it. But it's just my guess. Advancing the questions that my game has code that has influence to the problem. I can reproduce the problem with HelloWorld sample from the SDK.

I've just used OnDisable and also have black screen. However 1-2 times instead of listed exception I see:
03-31 14:11:24.390      191-211/? W/ActivityManager﹕ Activity pause timeout for ActivityRecord{4141bf90 com.gipnetix.esaga/com.unity3d.player.UnityPlayerNativeActivity}
03-31 14:11:26.155  31135-31135/? D/GoogleMobileAdsUnityPlugin﹕ Calling destroy() on Android
03-31 14:11:28.538      191-364/? E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!
03-31 14:11:33.546      191-230/? W/WindowManager﹕ Force clearing freeze: AppWindowToken{423583b8 token=Token{41860f98 ActivityRecord{4169aee0 com.gipnetix.esaga/com.unity3d.player.UnityPlayerNativeActivity}}}
03-31 14:11:38.241      191-211/? W/ActivityManager﹕ Activity destroy timeout for ActivityRecord{4141bf90 com.gipnetix.esaga/com.unity3d.player.UnityPlayerNativeActivity}
03-31 14:11:38.640      191-211/? W/ActivityManager﹕ Activity idle timeout for ActivityRecord{4169aee0 com.gipnetix.esaga/com.unity3d.player.UnityPlayerNativeActivity}

**Comment by jjjuande** [comment] 2015-03-31 12:22
Can you send me your Test Device ID (the device with the issue) to make an APK with the last version of Unity 5. I'll send you this APK and you can check if that problem still exists. (Just to make sure)
You'll find my email address on mi github profile.

**Comment by yuri-goncharov** [comment] 2015-03-31 13:38
The problem is reproducible on build with Unity 5.

**Comment by rampara** [comment] 2015-04-01 20:51
We are aware of this issue and it is partially fixed in the newest release of Google Play Services and will have a full fix in the next release to follow.

- Ram

**Closed** 2015-04-06 20:39 UTC
